packages:
  # all packages in direct subdirs of packages/
  # - './*'
  - 'apps/main'
  - 'libs/'
  # # all packages in subdirs of components/
  # - 'components/**'
  # # exclude packages that are inside test directories
  # - '!**/test/**'